FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy application code
COPY . .

# Generate Prisma Client
RUN npm run prisma:generate

EXPOSE 3006

CMD ["npm", "run", "start:dev"]
